### ISSUE TITLE
Peer to peer Code Review

### ISSUE THREAD

**Issue by StarMindz** [DebbyMiressa/Leaderboard#3]
# Impressive Code! 
### I must commend you for a clean, easy-to-understand, and professionally written Code. Keep up the good work. 
![](https://media.giphy.com/media/Jir7AUookJHIVb5aYM/giphy.gif)

### However here a thing to do to make your code even better:

- Deploy your project on GitHub pages to enable a live preview and also
- Consider updating your ReadMe file to contain a link to the live preview of your code hosted on GitHub pages.
Once this is done, you are good to go!!
Keep up the great work. Cheers 🥂🥂😉

**Comment by DebbyMiressa** [comment]
Thank you for the feeback! I will make sure to add the live demo ASAP. 👍
